config/routes.rb
Rails.application.routes.draw do
  resources :foruns do
    resources :posts
  end

  resources :posts do
    resources :comments
  end
  
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "join", to:"joins#new"
  post "join", to:"joins#create"
  delete "leave", to:"joins#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "user_posts", to: "pages#user_posts"

  get "user_comments", to: "pages#user_comments"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '' => 'pages#home'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:body).merge(commentdate:DateTime.now, username:Current.user.name, id_owner:Current.user.id))
    redirect_to post_path(@post)
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :commentdate, :username, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.id%>
  <div class="d-flex flex-column container card mt-4">
    <div class="d-flex card-header"> 
      <h3><%= comment.username %></h3>
      <h6 class="ms-auto"><%= comment.commentdate %></h6>
    </div>
    <div class="card-body">
        <div class="card-text"><%= comment.body %></div>
    </div>
    <% if Current.user.id === comment.id_owner%>
      <div class="ms-auto">
        <%= button_to "Destroy this comment", [comment.post, comment], method: :delete, class:"btn btn-outline-danger mt-2 mb-4" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post , @post.comments.build]) do |form| %>
  <div class="d-flex flex-column container">
    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body, class:"form-control" %>
    </div>

    <div class="ms-auto">
      <%= form.submit class:"btn btn-outline-primary mt-2 mb-4"%>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <% if Current.user.id === @comment.id_owner%>
    <%= button_to "Destroy this comment", @comment, method: :delete %>
  <% end %> 
</div>