config/routes.rb
Rails.application.routes.draw do
  resources :foruns do
    resources :posts
  end

  resources :posts do
    resources :comments
  end
  
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "join", to:"joins#new"
  post "join", to:"joins#create"
  delete "leave", to:"joins#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "user_posts", to: "pages#user_posts"

  get "user_comments", to: "pages#user_comments"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '' => 'pages#home'

end

app/models/forun.rb
class Forun < ApplicationRecord
    has_many :posts, dependent: :delete_all

    has_many :user_forun, dependent: :delete_all
    has_many :users, through: :user_forun
end

app/controllers/foruns_controller.rb
class ForunsController < ApplicationController
  before_action :set_forun, only: %i[ show edit update destroy ]
  @var = false

  # GET /foruns or /foruns.json
  def index
    @foruns = Forun.all
    @posts = Post.all
  end

  # GET /foruns/1 or /foruns/1.json
  def show
    @forun = Forun.find(params[:id])
    verify_user
  end

  def verify_user
    @forun = Forun.find(params[:id])
    @usr_frns = UserForun.all
    @usr_frns.each do |usr_frn|
      if usr_frn.user == Current.user && usr_frn.forun == @forun
        @var = true
      end
    end
  end

  # GET /foruns/new
  def new
    @forun = Forun.new
  end

  # GET /foruns/1/edit
  def edit
  end


  # POST /foruns or /foruns.json
  def create
    @forun = Forun.new(forun_params)
    @forun.id_owner = Current.user.id
    Current.user.foruns.push(@forun)
    respond_to do |format|
      if @forun.save
        format.html { redirect_to forun_url(@forun), notice: "Forun was successfully created." }
        format.json { render :show, status: :created, location: @forun }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @forun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foruns/1 or /foruns/1.json
  def update
    respond_to do |format|
      if @forun.update(forun_params)
        format.html { redirect_to forun_url(@forun), notice: "Forun was successfully updated." }
        format.json { render :show, status: :ok, location: @forun }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @forun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foruns/1 or /foruns/1.json
  def destroy
    @forun.posts.each do |post|
      post.destroy
    end
    @forun.destroy

    respond_to do |format|
      format.html { redirect_to foruns_url, notice: "Forun was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forun
      @forun = Forun.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forun_params
      params.require(:forun).permit(:nome, :topico, :id_owner)
    end
end

app/helpers/foruns_helper.rb
module ForunsHelper
end

app/views/foruns/_form.html.erb
<%= form_with(model: forun) do |form| %>
  <div class="d-flex flex-column">
    <% if forun.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(forun.errors.count, "error") %> prohibited this forun from being saved:</h2>

        <ul>
          <% forun.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :nome, style: "display: block" %>
      <%= form.text_field :nome, class:"form-control"%>
    </div>

    <div>
      <%= form.label :topico, style: "display: block" %>
      <%= form.text_field :topico, class:"form-control"%>
    </div>

    <div class="ms-auto">
      <%= form.submit class:"btn btn-outline-primary mt-3"%>
      <%= link_to "Back to home", "/", class:"btn btn-outline-secondary mt-3" %>
    </div>
  </div>
<% end %>

app/views/foruns/_forun.html.erb
<div class="card mt-4">
  <div class="d-flex card-header"> 
    <h6><%= forun.nome%></h6>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= forun.topico %></h5>
  </div>
</div>

app/views/foruns/edit.html.erb
<h1>Editing forun</h1>

<%= render "form", forun: @forun %>

<br>

<div>
  <%= link_to "Show this forun", @forun %> |
  <%= link_to "Back to foruns", foruns_path %>
</div>

app/views/foruns/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex flex-column justify-content-center container"> 
  <div class="d-flex">
    <h1>Forums:</h1>
    <div class="ms-auto">
      <%= link_to "New forum", new_forun_path, class:"btn btn-outline-primary"%>
    </div>
  </div>
  <br>
  <% @foruns.each do |forun| %>
    <div class="card mt-4">
      <div class="d-flex card-header"> 
        <h6><%= forun.nome%></h6>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= forun.topico %></h5>
      </div>
      <div class="d-flex card-footer justify-content-end">
        <%= link_to "Go to forum", forun , class:"btn btn-outline-primary"%>
      </div>
    </div>
  <% end %>
</div>

app/views/foruns/new.html.erb
<div class="d-flex flex-column container" style = "width: 40%">
  <h1>New forum</h1>
  <%= render "form", forun: @forun %>
</div>

app/views/foruns/show.html.erb
<div class="d-flex flex-column container">
  <div class="d-flex flex-column container">
    <%= render @forun %>
    
    <div class = "d-flex ms-auto">
      <%= link_to "Back to home", "/", class:"btn btn-outline-secondary mt-3" %>
      <% if Current.user.id == @forun.id_owner%>
        <%= button_to "Destroy this forum", @forun, method: :delete, class:"btn btn-outline-danger mt-3"%>
      <% end %>  
    </div>
    <br>
    <div class="d-flex flex-column container">
      <%if @var %>
        <div class = "d-flex ">
          <div class = "ms-auto">
            <%= render "posts/form"%>
          </div>
          <div class = "ms-auto">
            <% if Current.user.id != @forun.id_owner%>
              <%= render "joins/form_leave" , :forun => @forun %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class = "ms-auto">
        <%if !@var %>
          <%= render "joins/form" , :forun => @forun %>
        <% end %>
      </div>
      <div class="d-flex flex-column container" style = "width: 50%">
        <% @forun.posts.each do |post| %>
          <%if post != nil && post.id%>
            <%= render post %>
            <div class = "ms-auto">
              <%= link_to "Go to", post , class:"btn btn-outline-primary mt-4"%>
            </div>
          <% end %>
          <br>
          <br>
        <% end %>
      </div>
    </div>
  </div>
</div>