config/routes.rb
Rails.application.routes.draw do
  resources :foruns do
    resources :posts
  end

  resources :posts do
    resources :comments
  end
  
  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  get "join", to:"joins#new"
  post "join", to:"joins#create"
  delete "leave", to:"joins#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  get "user_posts", to: "pages#user_posts"

  get "user_comments", to: "pages#user_comments"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '' => 'pages#home'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", "/" , class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Forums", foruns_path, class:"nav-link active"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User Actions
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "My posts", "/user_posts" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "My comments", "/user_comments" %></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex container justify-content-center justify-content-evenly me-0" role="search">
        <div class="d-flex container justify-content-end" >
            <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-danger"%>
        </div>
      </div>
    </div>
  </div>
</nav>


      
      
      